### ISSUE TITLE
Issue bootstrapping Config API

### ISSUE THREAD

**Issue by ruiengana** [JanssenProject/jans-cloud-native#11]
In a clean CN install, we are getting an error bootstrapping config-api.

```
ERROR [io.qu.ru.Application] (main) Failed to start application (with profile prod): javax.ws.rs.WebApplicationException: Multiple UMA Scope with same name - https://jans.io/oauth/config/acrs.readonly
        at io.jans.configapi.auth.UmaResourceProtectionService.createScopeIfNeeded(UmaResourceProtectionService.java:104)
        at io.jans.configapi.auth.UmaResourceProtectionService.verifyResources(UmaResourceProtectionService.java:76)
        at io.jans.configapi.auth.UmaResourceProtectionService_ClientProxy.verifyResources(UmaResourceProtectionService_ClientProxy.zig:186)
        at io.jans.configapi.configuration.ConfigurationFactory.createAuthorizationService(ConfigurationFactory.java:300)
        at io.jans.configapi.configuration.ConfigurationFactory.create(ConfigurationFactory.java:158)
        at io.jans.configapi.configuration.ConfigurationFactory_ClientProxy.create(ConfigurationFactory_ClientProxy.zig:329)
        at io.jans.configapi.ConfigApiApplication.onStart(ConfigApiApplication.java:52)
        at io.jans.configapi.ConfigApiApplication_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(ConfigApiApplication_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:147)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
        at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:60)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy_0(LifecycleEventsBuildStep$startupEvent-858218658.zig:81)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy(LifecycleEventsBuildStep$startupEvent-858218658.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:631)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:95)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
        at io.jans.configapi.MainApp.main(MainApp.java:19)
```

NOTE: This didn't happened with 1.0.0_a2

**Comment by moabu** [comment]
Hey @ruiengana ,

This was an image build error . Just pull the image again and things should work.
